// src/common/constants/error-code.constants.ts

export const ERROR_CODES = {
  // Common
  NOT_FOUND: 'NOT_FOUND',
  BAD_REQUEST: 'BAD_REQUEST',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',

  // Auth
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  INVALID_TOKEN: 'INVALID_TOKEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',

  // Workspaces
  WORKSPACE_NOT_FOUND: 'WORKSPACE_NOT_FOUND',
  WORKSPACE_ACCESS_DENIED: 'WORKSPACE_ACCESS_DENIED',
  WORKSPACE_NAME_EXISTS: 'WORKSPACE_NAME_EXISTS',
  WORKSPACE_MEMBER_NOT_FOUND: 'WORKSPACE_MEMBER_NOT_FOUND',

  // Collections
  COLLECTION_NOT_FOUND: 'COLLECTION_NOT_FOUND',
  COLLECTION_NAME_EXISTS: 'COLLECTION_NAME_EXISTS',
  COLLECTION_NOT_IN_WORKSPACE: 'COLLECTION_NOT_IN_WORKSPACE',

  // Requests
  REQUEST_NOT_FOUND: 'REQUEST_NOT_FOUND',
  REQUEST_CREATE_FAILED: 'REQUEST_CREATE_FAILED',
  REQUEST_UPDATE_FAILED: 'REQUEST_UPDATE_FAILED',
  REQUEST_RUN_FAILED: 'REQUEST_RUN_FAILED',
  REQUEST_INVALID_URL: 'REQUEST_INVALID_URL',

  // Request Headers
  REQUEST_HEADER_NOT_FOUND: 'REQUEST_HEADER_NOT_FOUND',

  // Request Test Cases
  REQUEST_TESTCASE_NOT_FOUND: 'REQUEST_TESTCASE_NOT_FOUND',
  GENERATE_TEST_CASES_FAILED: 'GENERATE_TEST_CASES_FAILED',
  GENERATE_TEST_CASES_TIMEOUT: 'GENERATE_TEST_CASES_TIMEOUT',
  GENERATE_TEST_CASES_MODEL_UNREACHABLE:
    'GENERATE_TEST_CASES_MODEL_UNREACHABLE',
  INVALID_GENERATE_TEST_CASES_RESPONSE: 'INVALID_GENERATE_TEST_CASES_RESPONSE',

  // Environments / Variables
  ENVIRONMENT_NOT_FOUND: 'ENVIRONMENT_NOT_FOUND',
  ENVIRONMENT_NAME_EXISTS: 'ENVIRONMENT_NAME_EXISTS',
  VARIABLE_NOT_FOUND: 'VARIABLE_NOT_FOUND',
  VARIABLE_NAME_EXISTS: 'VARIABLE_NAME_EXISTS',

  // Flows
  FLOW_NOT_FOUND: 'FLOW_NOT_FOUND',
  FLOW_NODE_NOT_FOUND: 'FLOW_NODE_NOT_FOUND',
  FLOW_RUN_NOT_FOUND: 'FLOW_RUN_NOT_FOUND',
  FLOW_EXECUTION_FAILED: 'FLOW_EXECUTION_FAILED',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
